hardkills_list = ("Modelagem de Machine Learning",
              "Estatística avançada",
              "Análise de vulnerabilidades",
              "Arquitetura em AWS/Azure/GCP",
              "Automação com CI/CD",
              "Programação de smart contracts",
              "Programação embarcada",
              "Visão computacional",
              "Análise de sequências biológicas",
              "Modelagem e integração 3D")
softskills_list = ("Pensamento analítico",
                   "Comunicação de insights",
                   "Atenção aos detalhes",
                   "Planejamento estratégico",
                   "Trabalho em equipe",
                   "Pensamento lógico",
                   "Resolução de problemas",
                   "Tomada de decisão",
                   "Raciocínio crítico",
                   "Criatividade")
empregos_list = ("Engenheiro de IA",
"Cientista de Dados",
"Analista de Cibersegurança",
"Arquiteto de Cloud",
"Engenheiro de DevOps",
"Desenvolvedor Blockchain",
"Engenheiro de Robótica",
"Programador de Sistemas Autônomos",
"Bioinformata",
"Desenvolvedor AR/VR")